sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 10yNGadhksBiuk7YAjNwbUAl8csd42sc/dlq8er9xwx4u7l5JM/y3ELLZY2pqstJUFp8xQnuhiFcg5AUeuRQ6sDQyonbipj4IYf9bozVUyD7c0eTDmDaXKIUdGcE3X3Wjmt7DKKnRnWp4sxg7OXcPsIFXN0KWmRO0cUYGhxN0nVlbYdwYdZQVrwN8mVWojG006wdR6Wd+E/v2FVTj8BkIAMOwFXmU1jGYxKGpVoyFbtDBiMeZA0h3R9ZUlRTo+xf4kLT3v3KXsOLzu7VmRzw+jVr8PMK3h4RVx602Mln/StIAYe/N6zU1DBwpy3FIO1cRX6+yVlzqE8TRTHRJouJGstL7NIvk9LNiiwCGZnqza9xspCwxKCtzSf6aImLdar8Mdp9VCQp7xYbFdWIYVd2p7jfJYHV8jvaooTnlW3GjsiwiLJUIHwao7MHTSfAqO6BCi4ZM9m50bkCtMCAg7YPBbxv946aV7QMkWiz/Nu1x54ITMy7lJjlMCNSk9eyire82AJa8W49SWm6cuDADXWeOoK74kXs9g+mHctW1WmaFW/KNVbd66dzUUIS5IhnPhxzhxkbxePD5PbMaRWY3UvwiwLSp0vURyJVTlA2yBPQjkl9LtfUD7nrbDZT2vZkIlE8T//ZOJGUWLb7oLJqkv4jbsWuEBCyNgeYfm4RA4ddYYo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Ear-in-the-Wall_5150
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy